### ISSUE TITLE
faster / more robust implementation

### ISSUE THREAD

**Issue by ORESoftware** [ljharb/is-generator-function#7]
Been using this lib for awhile, no problems so far, but do you see anything wrong with the following implementation?
```js

    isGeneratorFn: function(fn){
        const str = String(fn);
        const indexOfFirstParen = str.indexOf('(');
        const indexOfFirstStar = str.indexOf('*');
        return indexOfFirstStar < indexOfFirstParen;
    },
```

not sure if it's faster, but probably less convoluted logic and possibly won't break if underlying stuff changes. You are calling toString on fn in your logic, just like I do, which seems like the most expensive thing in both our implementations. but I believe the above implementation is both simpler and more robust.

**Comment by ljharb** [comment]
`String(fn)` can be overridden with `.toString`, so you'd need to cache `Function.prototype.toString` and `.call` it on the function - but that's not a big deal to fix (same with caching `String.prototype.indexOf`)

You'd also still first need https://github.com/ljharb/is-generator-function/blob/master/index.js#L8 to filter out non-functions.

It's a fair point though that the `(fnStr === '[object Function]' || fnStr === '[object GeneratorFunction]')` test isn't providing much value, because `Symbol.toStringTag` could be overriding it.

I'll think about modifying the implementation a bit based on your suggestions.

**Comment by the1mills** [comment]
Yeah my code was just a thought, mine is not super well tested. Not sure if I am following how String() or indexOf() would get manipulated..and also just because they are cached at top of file doesnt mean they couldn't get overridden before this file was loaded, by user code?

**Comment by ljharb** [comment]
You're correct - in JS, you can only protect yourself against code that runs after you - like `delete String.prototype.indexOf`, for example.

**Comment by ljharb** [comment]
It turns out that in some versions of Safari, `(function* foo() {}).toString()` outputs `function foo() {}`, so while using the toString value is a good signal for `true`, it's not sufficient to test for `false`.

I'll close this now, but I'll definitely need to update the implementation so it can pass in engines like Safari.

**Comment by the1mills** [comment]
oh weird, so the * character gets removed, but it's still a generator function? bizarro

**Comment by the1mills** [comment]
what if you call` String(function* foo() {})` in safari? Shouldn't make a difference, just curious.

**Comment by ljharb** [comment]
You get the star removed.

**Comment by ljharb** [comment]
See v1.0.6 for the updated implementation.
